name: Docker build - JBrowse Web
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and push JBrowse Web Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./jbrowse-web.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jbrowse-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/jbrowse-web:${{env.RELEASE_VERSION}}
